BEASISWA_daftarpenerima/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name = 'index'),
	]

BEASISWA_daftarskema/urls.py
from django.conf.urls import url
from .views import index, daftar_skema, daftar_tambah

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^daftar_skema/', daftar_skema, name = 'daftar_skema'),
    url(r'^daftar_tambah/', daftar_tambah, name = 'daftar_tambah')


]

BEASISWA_lihataktif/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name = 'index'),
	
]

BEASISWA_lihatpendaftar/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name = 'index'),
	
]

BEASISWA_lihatpenerima/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name = 'index'),
	
]

landingpage/urls.py
from django.conf.urls import url
from .views import index, login, register_mahasiswa, register_donatur, register_donatur_individual, register_donatur_yayasan

app_name = 'landingpage'

urlpatterns = [
	url(r'^$', index, name = 'index'),
	url(r'^login/', login, name = 'login'),
	url(r'^register-mahasiswa/', register_mahasiswa, name = 'register-mahasiswa'),
	url(r'^register-donatur/', register_donatur, name = 'register-donatur'),	
	url(r'^register-donatur-individual', register_donatur_individual, name = 'register-donatur-individual')	,
	url(r'^register-donatur-yayasan', register_donatur_yayasan, name = 'register-donatur-yayasan')	

]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import landingpage.urls as landingpage
import BEASISWA_daftarskema.urls as optionskema
import BEASISWA_lihataktif.urls as lihataktif
import BEASISWA_daftarpenerima.urls as daftarpenerima
import BEASISWA_lihatpendaftar.urls as lihatpendaftar
import BEASISWA_lihatpenerima.urls as lihatpenerima

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(landingpage, namespace='landingpage')),
    url(r'^optionskema/', include(optionskema, namespace='optionskema')),
    url(r'^lihataktif/', include(lihataktif, namespace='lihataktif')),
    url(r'^daftarpenerima/', include(daftarpenerima, namespace='daftarpenerima')),    
    url(r'^lihatpendaftar/', include(lihatpendaftar, namespace='lihatpendaftar')),
    url(r'^lihatpenerima/', include(lihatpenerima, namespace='lihatpenerima')),
]

BEASISWA_daftarpenerima/models.py
from django.db import models

# Create your models here.

BEASISWA_daftarskema/models.py
from django.db import models

# Create your models here.

BEASISWA_lihataktif/models.py
from django.db import models

# Create your models here.

BEASISWA_lihatpendaftar/models.py
from django.db import models

# Create your models here.

BEASISWA_lihatpenerima/models.py
from django.db import models

# Create your models here.

landingpage/models.py
from django.db import models

# Create your models here.

BEASISWA_daftarpenerima/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	response = {}
	return render(request, 'checkout.html', response)

BEASISWA_daftarskema/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	response = {}
	return render(request, 'option.html', response)

def daftar_skema(request):
	
	return render(request, 'daftar_skema.html', response)

def daftar_tambah(request):

	return render(request, 'daftar_tambah.html', response)

BEASISWA_lihataktif/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	response = {}
	return render(request, 'dashboard.html', response)

def detail(request):
	
	return render(request, 'detail.html', response)

BEASISWA_lihatpendaftar/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	response = {}
	return render(request, 'dashboards.html', response)

BEASISWA_lihatpenerima/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	response = {}
	return render(request, 'dashboardss.html', response)

landingpage/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse


# Create your views here.
def index(request):
	html = loader.get_template('landingpage.html')
	context = {

	}
	return HttpResponse(html.render(context, request))

def login(request):
	html = loader.get_template('login.html')
	context = {

	}
	return HttpResponse(html.render(context, request))

def register_mahasiswa(request):
	html = loader.get_template('register-mahasiswa.html')
	context = {

	}
	return HttpResponse(html.render(context, request))

def register_donatur(request):
	html = loader.get_template('register-donatur.html')
	context = {

	}
	return HttpResponse(html.render(context, request))

def register_donatur_individual(request):
	html = loader.get_template('register-donatur-individual.html')
	context = {

	}
	return HttpResponse(html.render(context, request))

def register_donatur_yayasan(request):
	html = loader.get_template('register-donatur-yayasan.html')
	context = {

	}
	return HttpResponse(html.render(context, request))

BEASISWA_daftarpenerima/templates/_pgbackup/checkout_1525683106.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Checkout example for Bootstrap</title>
        <!-- Bootstrap core CSS -->
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="form-validation.css" rel="stylesheet">
    </head>
    <body class="bg-light">
        <div class="container">
            <div class="py-5 text-center">
                <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
                <h2 class="text-left">FORM PENDAFTARAN BEASISWA</h2>
                <p class="lead"></p>
            </div>
            <div class="row">
                <div class="col-md-8 order-md-1">
                    <h4 class="mb-3"><br></h4> 
                    <form class="needs-validation" novalidate="">
                        <div class="row">
</div>
                        <div class="mb-3">Kode Beasiswa&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
                            <br>
                            <div class="input-group">
                                <div class="input-group-prepend">
</div>
                                <input type="text" class="form-control" id="username" placeholder="Automatically insert by system" required="">
                                <div class="invalid-feedback" style="width: 100%;">
                                    Your username is required.
</div>
                            </div>
                        </div>
                        <div class="mb-3">NPM
                            <br>
                            <div class="input-group">
                                <div class="input-group-prepend">
</div>
                                <input type="text" class="form-control" placeholder="Automatically insert by system" required="">
                                <div class="invalid-feedback" style="width: 100%;">
                                    Your username is required.
</div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="email">Email 
                                <span class="text-muted">(Optional)</span>
                            </label>
                            <input type="email" class="form-control" id="email" placeholder="Automatically insert by system">
                            <div class="invalid-feedback">
                                Please enter a valid email address for shipping updates.
</div>
                        </div>
                        <div class="mb-3">
                            <label for="address">Indeks Prestasi Semester</label>
                            <input type="text" class="form-control" id="address" placeholder="0.00 " required="">
                            <div class="invalid-feedback">
                                Please enter your shipping address.
</div>
                        </div>
                        <div class="row">
</div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
                        <hr class="mb-4">
                        <div class="d-block my-3">
</div>
                        <div class="row">
</div>
                    </form>
                </div>
            </div>
            <footer class="my-5 pt-5 text-muted text-center text-small">
                <p class="mb-1 text-left">© 2017-2018&nbsp;</p>
                <ul class="list-inline text-left">
                    <li class="list-inline-item">
                        <a href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Terms</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Support</a>
                    </li>
                </ul>
            </footer>
        </div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/popper.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
    <body class="bg-light">
        <div class="container">
</div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/popper.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>

BEASISWA_daftarpenerima/templates/_pgbackup/checkout_1525689852.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Checkout example for Bootstrap</title>
        <!-- Bootstrap core CSS -->
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="form-validation.css" rel="stylesheet">
    </head>
    <body class="bg-light">
        <nav class="navbar navbar-expand-lg navbar-light bg-dark text-light"> 
            <a class="navbar-brand text-light" href="#">SIMBION</a> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler26" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation"> 
                <span class="navbar-toggler-icon"></span> 
            </button>             
            <div class="collapse navbar-collapse" id="navbarToggler26"> 
                <form class="form-inline my-2 my-lg-0"> 
</form>                 
            </div>             
        </nav>
        <div class="container">
            <div class="py-5 text-center">
                <p class="lead"></p>
                <h2 class="text-left">FORM PENDAFTARAN BEASISWA</h2>
            </div>
            <div class="row">
                <div class="col-md-8 order-md-1">
                    <h4 class="mb-3"><br></h4> 
                    <form class="needs-validation" novalidate="">
                        <div class="row">
</div>
                        <div class="mb-3">Kode Beasiswa&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
                            <br>
                            <div class="input-group">
                                <div class="input-group-prepend">
</div>
                                <input type="text" class="form-control" id="username" placeholder="20182019128" required="">
                                <div class="invalid-feedback" style="width: 100%;">
                                    Your username is required.
</div>
                            </div>
                        </div>
                        <div class="mb-3">NPM
                            <br>
                            <div class="input-group">
                                <div class="input-group-prepend">
</div>
                                <input type="text" class="form-control" placeholder="1606912345" required="">
                                <div class="invalid-feedback" style="width: 100%;">
                                    Your username is required.
</div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="email">Email 
                                <span class="text-muted">(Optional)</span>
                            </label>
                            <input type="email" class="form-control" id="email" placeholder="xx@ui.ac.id">
                            <div class="invalid-feedback">
                                Please enter a valid email address for shipping updates.
</div>
                        </div>
                        <div class="mb-3">
                            <label for="address">Indeks Prestasi Semester</label>
                            <input type="text" class="form-control" id="address" placeholder="3.99 " required="">
                            <div class="invalid-feedback">
                                Please enter your shipping address.
</div>
                        </div>
                        <div class="row">
</div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
                        <hr class="mb-4">
                        <div class="d-block my-3">
</div>
                        <div class="row">
</div>
                    </form>
                </div>
            </div>
            <footer class="my-5 pt-5 text-muted text-center text-small">
                <p class="mb-1 text-left">© 2017-2018&nbsp;</p>
                <ul class="list-inline text-left">
                    <li class="list-inline-item">
                        <a href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Terms</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Support</a>
                    </li>
                </ul>
            </footer>
        </div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/popper.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
    <body class="bg-light">
        <div class="container">
</div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/popper.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>

BEASISWA_daftarpenerima/templates/_pgbackup/checkout_1525689896.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Checkout example for Bootstrap</title>
        <!-- Bootstrap core CSS -->
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="form-validation.css" rel="stylesheet">
    </head>
    <body class="bg-light">
        <nav class="navbar navbar-expand-lg navbar-light bg-dark text-light"> 
            <a class="navbar-brand text-light" href="#">SIMBION</a> 
            <div id="navbar" class="navbar-collapse collapse">
                <form class="navbar-form">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>
            </div>             
        </nav>
        <div class="container">
            <div class="py-5 text-center">
                <p class="lead"></p>
                <h2 class="text-left">FORM PENDAFTARAN BEASISWA</h2>
            </div>
            <div class="row">
                <div class="col-md-8 order-md-1">
                    <h4 class="mb-3"><br></h4> 
                    <form class="needs-validation" novalidate="">
                        <div class="row">
</div>
                        <div class="mb-3">Kode Beasiswa&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
                            <br>
                            <div class="input-group">
                                <div class="input-group-prepend">
</div>
                                <input type="text" class="form-control" id="username" placeholder="20182019128" required="">
                                <div class="invalid-feedback" style="width: 100%;">
                                    Your username is required.
</div>
                            </div>
                        </div>
                        <div class="mb-3">NPM
                            <br>
                            <div class="input-group">
                                <div class="input-group-prepend">
</div>
                                <input type="text" class="form-control" placeholder="1606912345" required="">
                                <div class="invalid-feedback" style="width: 100%;">
                                    Your username is required.
</div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="email">Email 
                                <span class="text-muted">(Optional)</span>
                            </label>
                            <input type="email" class="form-control" id="email" placeholder="xx@ui.ac.id">
                            <div class="invalid-feedback">
                                Please enter a valid email address for shipping updates.
</div>
                        </div>
                        <div class="mb-3">
                            <label for="address">Indeks Prestasi Semester</label>
                            <input type="text" class="form-control" id="address" placeholder="3.99 " required="">
                            <div class="invalid-feedback">
                                Please enter your shipping address.
</div>
                        </div>
                        <div class="row">
</div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
                        <hr class="mb-4">
                        <div class="d-block my-3">
</div>
                        <div class="row">
</div>
                    </form>
                </div>
            </div>
            <footer class="my-5 pt-5 text-muted text-center text-small">
                <p class="mb-1 text-left">© 2017-2018&nbsp;</p>
                <ul class="list-inline text-left">
                    <li class="list-inline-item">
                        <a href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Terms</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Support</a>
                    </li>
                </ul>
            </footer>
        </div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/popper.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
    <body class="bg-light">
        <div class="container">
</div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/popper.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>

BEASISWA_daftarskema/templates/_pgbackup/daftar_skema_1525674683.html
{% extends "navbar.html" %}

{%load staticfiles%}

{%block title%}
  <title>Register Paket Beasiswa</title>
{%endblock%}

{%block head%}
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{%endblock%}

{%block body%}
  <div class="grid">

    <form action="/" method="post" class="form login">

      <header class="login__header">
        <h3 class="login__title">Register Mahasiswa</h3>
      </header>

      <div class="login__body">

        <div class="form__field"> Username
          <input type="username" placeholder="Username" required>
        </div>         
        
        <div class="form__field"> Password
          <input type="Password" placeholder="Password" required>
        </div> 

        <div class="form__field"> NPM
          <input type="text" placeholder="NPM" required>
        </div>

        <div class="form__field"> Email
          <input type="email" placeholder="Email" required>
        </div>
        
        <div class="form__field"> Nama Lengkap
          <input type="text" placeholder="Nama" required>
        </div>

        <div class="form__field"> Nomor Telepon
          <input type="tel" placeholder="No Telp" required>
        </div> 

        <div class="form__field"> Alamat Tempat Tinggal
          <input type="text" placeholder="Alamat Tinggal">
        </div>

        <div class="form__field"> Alamat Domisili
          <input type="text" placeholder="Alamat Domisili" required>
        </div>
        
        <div class="form__field"> Instansi Bank
          <input type="text" placeholder="Nama Bank" required>
        </div>

        <div class="form__field"> Nomor Rekening
          <input type="text" placeholder="Nomor Rekening" required>
        </div> 

        <div class="form__field"> Nama Pemilik
          <input type="text" placeholder="Nama Pemilik" required>
        </div>
      
      </div>

      <footer class="login__footer">
        <input type="submit" value="Register">
      </footer>

    </form>

  </div>

{%endblock%}

BEASISWA_daftarskema/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>Sistem Beasiswa Online</title>
  {% endblock %}
 
  <link rel="icon" href= "https://thumb.ibb.co/jCLfKS/Screenshot_1.png">

  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:900" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
    body{
       background-color: #eaeaea
    }
  	.navbar{
  		border-radius: 0;
      background-color: #202021;
      border-color: #202021;
  	}
  	#navbar-brand{
  		font-family: Lato:900;
  		font-size: 25px;
  	}
  	.nav{
  		font-family: Montserrat;
  		font-size: 18px;
  	}
  </style>

  {%block head%}
  {%endblock%}

</head>

<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid"> 

      <ul class="nav navbar-nav">
      {%with url_name=request.resolver_match.url_name%}
        <li class ="{% if url_name == 'index' %}active{% endif %}" id = "navbar-brand"><a href="{% url 'landingpage:index' %}"> SIMBION </a></li>
        <li><a href="#"><span class="glyphicon glyphicon-list-alt"></span> Pengumuman </a></li>     
      {%endwith%}
		  </ul>

      <ul class="nav navbar-nav navbar-right">
        {%with url_name=request.resolver_match.url_name%}
        <li class="dropdown {% if url_name == 'register-donatur' %}active{% endif %} {% if url_name == 'register-mahasiswa' %}active{% endif %}">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="glyphicon glyphicon-user"></span> Register <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'landingpage:register-donatur' %}">Donatur</a></li>
            <li><a href="{% url 'landingpage:register-mahasiswa' %}">Mahasiswa</a></li>
          </ul>
        </li>
        <li class="{% if url_name == 'login' %}active{% endif %}">
          <a href="{% url 'landingpage:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login </a>
        </li>
        {%endwith%}
      </ul>

	  </div>
	</nav>
  {%block body%}
  {%endblock%}
</body>

</html>

landingpage/templates/landingpage.html
{% extends "navbar.html" %}

{%block title%}
  <title>Sistem Beasiswa Online</title>
{%endblock%}

{%block content%}
	<h1>disini list beasiswa</h1>
{%endblock%}

landingpage/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>Sistem Beasiswa Online</title>
  {% endblock %}
 
  <link rel="icon" href= "https://thumb.ibb.co/jCLfKS/Screenshot_1.png">

  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:900" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
    body{
       background-color: #eaeaea
    }
  	.navbar{
  		border-radius: 0;
      background-color: #202021;
      border-color: #202021;
  	}
  	#navbar-brand{
  		font-family: Lato:900;
  		font-size: 25px;
  	}
  	.nav{
  		font-family: Montserrat;
  		font-size: 18px;
  	}
  </style>

  {%block head%}
  {%endblock%}

</head>

<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid"> 

      <ul class="nav navbar-nav">
      {%with url_name=request.resolver_match.url_name%}
        <li class ="{% if url_name == 'index' %}active{% endif %}" id = "navbar-brand"><a href="{% url 'landingpage:index' %}"> SIMBION </a></li>
        <li><a href="#"><span class="glyphicon glyphicon-list-alt"></span> Pengumuman </a></li>     
      {%endwith%}
		  </ul>

      <ul class="nav navbar-nav navbar-right">
        {%with url_name=request.resolver_match.url_name%}
        <li class="dropdown {% if url_name == 'register-donatur' %}active{% endif %} {% if url_name == 'register-mahasiswa' %}active{% endif %}">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="glyphicon glyphicon-user"></span> Register <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'landingpage:register-donatur' %}">Donatur</a></li>
            <li><a href="{% url 'landingpage:register-mahasiswa' %}">Mahasiswa</a></li>
          </ul>
        </li>
        <li class="{% if url_name == 'login' %}active{% endif %}">
          <a href="{% url 'landingpage:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login </a>
        </li>
        {%endwith%}
      </ul>

	  </div>
	</nav>
  {%block body%}
  {%endblock%}
</body>

</html>

landingpage/templates/register-donatur.html
{% extends "navbar.html" %}

{%block title%}
  <title>Register Donatur</title>
{%endblock%}

{%block head%}
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

	<style>
		.center-div{
			padding-top: 150px;
			text-align:center;
		}
		.button {
		    background-color: #4CAF50; /* Green */
		    border: none;
		    color: white;
		    padding: 15px 32px;
		    text-align: center;
		    text-decoration: none;
		    display: inline-block;
		    font-size: 20px;
		    font-family: 'Montserrat';
		    background-color: #1dabb8;
		    margin: 4px 2px;
		    cursor: pointer;
		    -webkit-transition-duration: 0.4s; /* Safari */
		    transition-duration: 0.4s;
		    width: 200px;
		}

		.button1:hover {
		    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
		    background-color: #198d98;
		}

		a:link {
	    color: white; 
	    background-color: transparent; 
	    text-decoration: none;
		}

	</style>
{%endblock%}

{%block body%}
  <div class="center-div">
    <button class="button button1"><a href="{% url 'landingpage:register-donatur-individual' %}">Individual</a></button>
    <button class="button button1"><a href="{% url 'landingpage:register-donatur-yayasan' %}">Yayasan</a></button>
  </div>
{%endblock%}